import = [
  "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[shell] 
program = "/bin/zsh"
args = ["-l"]

[window]
opacity = 0.9
dynamic_padding = true
blur = true
decorations = "None"

[window.padding]
x = 2
y = 2

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font]
size = 16

